In [3]:
import tensorflow as tf

## String Tensors

In [7]:
s = tf.constant("mángó")
s

<tf.Tensor: shape=(), dtype=string, numpy=b'm\xc3\xa1ng\xc3\xb3'>

In [9]:
tf.strings.length(s, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [18]:
i = tf.strings.unicode_decode(s, "UTF8")
i

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([109, 225, 110, 103, 243], dtype=int32)>

In [16]:
tf.strings.unicode_encode(i, "UTF-8")

<tf.Tensor: shape=(), dtype=string, numpy=b'm\xc3\xa1ng\xc3\xb3'>

In [50]:
t = tf.constant(["apple", "bánana", "µáßð", "جون سينا", "约翰塞纳", "ジョン・シナ", "Джон Сина"])
t

<tf.Tensor: shape=(7,), dtype=string, numpy=
array([b'apple', b'b\xc3\xa1nana', b'\xc2\xb5\xc3\xa1\xc3\x9f\xc3\xb0',
       b'\xd8\xac\xd9\x88\xd9\x86 \xd8\xb3\xd9\x8a\xd9\x86\xd8\xa7',
       b'\xe7\xba\xa6\xe7\xbf\xb0\xe5\xa1\x9e\xe7\xba\xb3',
       b'\xe3\x82\xb8\xe3\x83\xa7\xe3\x83\xb3\xe3\x83\xbb\xe3\x82\xb7\xe3\x83\x8a',
       b'\xd0\x94\xd0\xb6\xd0\xbe\xd0\xbd \xd0\xa1\xd0\xb8\xd0\xbd\xd0\xb0'],
      dtype=object)>

In [51]:
r = tf.strings.unicode_decode(t, "UTF8")
r

<tf.RaggedTensor [[97, 112, 112, 108, 101], [98, 225, 110, 97, 110, 97],
 [181, 225, 223, 240], [1580, 1608, 1606, 32, 1587, 1610, 1606, 1575],
 [32422, 32752, 22622, 32435], [12472, 12519, 12531, 12539, 12471, 12490],
 [1044, 1078, 1086, 1085, 32, 1057, 1080, 1085, 1072]]>

In [45]:
tf.strings.unicode_encode(r[0], "UTF-8")

<tf.Tensor: shape=(), dtype=string, numpy=b'apple'>

## Ragged Tensors

In [46]:
r[0]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 97, 112, 112, 108, 101], dtype=int32)>

In [48]:
r[:1]

<tf.RaggedTensor [[97, 112, 112, 108, 101]]>

In [52]:
r.to_tensor()

<tf.Tensor: shape=(7, 9), dtype=int32, numpy=
array([[   97,   112,   112,   108,   101,     0,     0,     0,     0],
       [   98,   225,   110,    97,   110,    97,     0,     0,     0],
       [  181,   225,   223,   240,     0,     0,     0,     0,     0],
       [ 1580,  1608,  1606,    32,  1587,  1610,  1606,  1575,     0],
       [32422, 32752, 22622, 32435,     0,     0,     0,     0,     0],
       [12472, 12519, 12531, 12539, 12471, 12490,     0,     0,     0],
       [ 1044,  1078,  1086,  1085,    32,  1057,  1080,  1085,  1072]],
      dtype=int32)>

In [63]:
r2 = tf.ragged.constant([[1, 1, 1, 1], [2, 2, 2], [3, 3], [4]])
tf.concat([r, r2], axis=0)

<tf.RaggedTensor [[97, 112, 112, 108, 101], [98, 225, 110, 97, 110, 97],
 [181, 225, 223, 240], [1580, 1608, 1606, 32, 1587, 1610, 1606, 1575],
 [32422, 32752, 22622, 32435], [12472, 12519, 12531, 12539, 12471, 12490],
 [1044, 1078, 1086, 1085, 32, 1057, 1080, 1085, 1072], [1, 1, 1, 1],
 [2, 2, 2], [3, 3], [4]]>

In [60]:
r2 = tf.ragged.constant([[1, 1, 1, 1], [2, 2, 2], [3, 3], [4], [], [], []])
tf.concat([r, r2], axis=1)

<tf.RaggedTensor [[97, 112, 112, 108, 101, 1, 1, 1, 1],
 [98, 225, 110, 97, 110, 97, 2, 2, 2], [181, 225, 223, 240, 3, 3],
 [1580, 1608, 1606, 32, 1587, 1610, 1606, 1575, 4],
 [32422, 32752, 22622, 32435], [12472, 12519, 12531, 12539, 12471, 12490],
 [1044, 1078, 1086, 1085, 32, 1057, 1080, 1085, 1072]]>

In [117]:
mr = tf.ragged.constant(
    [
        [[1] * 3, [2] * 2, [3]],
        [[4] * 4, [5] * 5, [6] * 6, [7] * 7],
    ]
)

In [118]:
mr

<tf.RaggedTensor [[[1, 1, 1], [2, 2], [3]],
 [[4, 4, 4, 4], [5, 5, 5, 5, 5], [6, 6, 6, 6, 6, 6], [7, 7, 7, 7, 7, 7, 7]]]>

In [119]:
tf.RaggedTensor.from_nested_row_splits(
    flat_values=[3, 1, 4, 1, 5, 9, 2, 6],
    nested_row_splits=[[0, 2, 3], [0, 3, 3, 5], [0, 4, 4, 7, 8, 8]],
).to_tensor()

<tf.Tensor: shape=(2, 2, 3, 4), dtype=int32, numpy=
array([[[[3, 1, 4, 1],
         [0, 0, 0, 0],
         [5, 9, 2, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[6, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int32)>

## Sparse Tensors

In [53]:
sp = r.to_sparse()

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [5 0]
 [5 1]
 [5 2]
 [5 3]
 [5 4]
 [5 5]
 [6 0]
 [6 1]
 [6 2]
 [6 3]
 [6 4]
 [6 5]
 [6 6]
 [6 7]
 [6 8]], shape=(42, 2), dtype=int64), values=tf.Tensor(
[   97   112   112   108   101    98   225   110    97   110    97   181
   225   223   240  1580  1608  1606    32  1587  1610  1606  1575 32422
 32752 22622 32435 12472 12519 12531 12539 12471 12490  1044  1078  1086
  1085    32  1057  1080  1085  1072], shape=(42,), dtype=int32), dense_shape=tf.Tensor([7 9], shape=(2,), dtype=int64))

In [132]:
sp2 = tf.SparseTensor(
    indices=([0, 1], [1, 0], [2, 0]), values=[1, 2, 3], dense_shape=[3, 2]
)
sp2

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 2], shape=(2,), dtype=int64))

In [130]:
tf.sparse.to_dense(sp)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 0],
       [3, 0]], dtype=int32)>

In [133]:
sp3 = tf.SparseTensor(
    indices=([1, 1], [0, 1], [2, 0]), values=[1, 2, 3], dense_shape=[3, 2]
)
sp3

SparseTensor(indices=tf.Tensor(
[[1 1]
 [0 1]
 [2 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 2], shape=(2,), dtype=int64))

In [138]:
tf.sparse.to_dense(tf.sparse.reorder(sp3))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 2],
       [0, 1],
       [3, 0]], dtype=int32)>

## TensorArray

In [140]:
ta = tf.TensorArray(dtype=tf.float32, size=2)

In [158]:
tf.TensorArray?

Init signature:
tf.TensorArray(
    dtype,
    size=None,
    dynamic_size=None,
    clear_after_read=None,
    tensor_array_name=None,
    handle=None,
    flow=None,
    infer_shape=True,
    element_shape=None,
    colocate_with_first_write_call=True,
    name=None,
)
Docstring:     
Class wrapping dynamic-sized, per-time-step, Tensor arrays.

This class is meant to be used with dynamic iteration primitives such as
`while_loop` and `map_fn`.  It supports gradient back-propagation via special
"flow" control flow dependencies.

Note that although the array can be read multiple times and positions can be
overwritten, behavior may be undefined when storing multiple references to
the same array and clear_after_read is False. In particular, avoid using
methods like concat() to convert an intermediate TensorArray to a Tensor,
then further modifying the TensorArray, particularly if you need to backprop
through it later.

Example 1: Plain reading and writing.

>>> ta = tf.TensorArray(tf.floa

In [157]:
ta = ta.write(0, 11)
ta = ta.write(1, 12)
ta = ta.write(2, 13)
ta.read(1)

OutOfRangeError: Tried to write to index 2 but array is not resizeable and size is: 2 

In [147]:
ta.write?

Signature: ta.write(index, value, name=None)
Docstring:
Write `value` into index `index` of the TensorArray.

Args:
  index: 0-D.  int32 scalar with the index to write to.
  value: N-D.  Tensor of type `dtype`.  The Tensor to write to this index.
  name: A name for the operation (optional).

Returns:
  A new TensorArray object with flow that ensures the write occurs.
  Use this object for all subsequent operations.

Raises:
  ValueError: if there are more writers than specified.


Note: The output of this function should be used. If it is not, a warning will be logged or an error may be raised. To mark the output as used, call its .mark_used() method.
File:      ~/Coding_Playground/Machine_Learning/Hands_on_Machine_Learning/.micromamba/envs/homl/lib/python3.10/site-packages/tensorflow/python/ops/tensor_array_ops.py
Type:      method

## `tf.function` and `tf.concrete_function`

In [77]:
import tensorflow as tf


@tf.function(reduce_retracing=True)
def cube(x):
    print("Tracing...")
    print(f"x = {x}")
    return x**3

In [78]:
cube, cube.python_function

(<tensorflow.python.eager.polymorphic_function.polymorphic_function.Function at 0x7ffd94639db0>,
 <function __main__.cube(x)>)

In [79]:
cube(10)

Tracing...
x = 10


<tf.Tensor: shape=(), dtype=int32, numpy=1000>

In [80]:
cube.get_concrete_function(tf.constant(10))

Tracing...
x = Tensor("x:0", shape=(), dtype=int32)


<ConcreteFunction cube(x) at 0x7FFDDC32D840>

In [15]:
cube.get_concrete_function(10) is cube.get_concrete_function(11)

False

In [16]:
cube.get_concrete_function(tf.constant(10)) is cube.get_concrete_function(
    tf.constant(11)
)

True

In [17]:
cube.get_concrete_function(tf.constant(10)) is cube.get_concrete_function(
    tf.constant(11, dtype=tf.float32)
)

False

In [25]:
try:
    cube.get_concrete_function(10)(11)
except TypeError as err:
    print(err)

Binding inputs to tf.function failed due to `Can not cast 11 to Literal(value=10)`. Received args: (11,) and kwargs: {} for signature: (x: Literal(value=10)) -> TensorSpec(shape=(), dtype=tf.int32, name=None).
Fallback to flat signature also failed due to: cube() takes 0 positional arguments, got 1.


In [34]:
try:
    cube.get_concrete_function(tf.constant(10.0))(tf.constant(11, dtype=tf.int32))
except tf.errors.InvalidArgumentError as err:
    print(err)

cannot compute __inference_cube_31 as input #0(zero-based) was expected to be a float tensor but is a int32 tensor [Op:__inference_cube_31]


In [43]:
cube.get_concrete_function(tf.constant(10.0))(4)

<tf.Tensor: shape=(), dtype=float32, numpy=64.0>

In [55]:
cube(7.0)

Tracing...


<tf.Tensor: shape=(), dtype=float32, numpy=343.0>

In [56]:
cube(7)

<tf.Tensor: shape=(), dtype=float32, numpy=343.0>

In [57]:
cube(7.5)

Tracing...


<tf.Tensor: shape=(), dtype=float32, numpy=421.875>

In [58]:
cube(tf.constant(7.0))

Tracing...


<tf.Tensor: shape=(), dtype=float32, numpy=342.99997>

## Exploring Graphs

In [68]:
cf = cube.get_concrete_function(tf.constant([420, 69], dtype=tf.int32))

Tracing...


In [69]:
cf.graph

In [70]:
cf.graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'pow/y' type=Const>,
 <tf.Operation 'pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [71]:
cf.graph.get_operation_by_name("pow/y")

<tf.Operation 'pow/y' type=Const>

In [72]:
cf.graph.get_tensor_by_name("pow:0")

<tf.Tensor 'pow:0' shape=(2,) dtype=int32>

In [75]:
type(cf.function_def)

tensorflow.core.framework.function_pb2.FunctionDef

In [76]:
cf.function_def

signature {
  name: "__inference_cube_167"
  input_arg {
    name: "x"
    type: DT_INT32
  }
  output_arg {
    name: "identity"
    type: DT_INT32
  }
}
node_def {
  name: "pow/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node_def {
  name: "pow"
  op: "Pow"
  input: "x"
  input: "pow/y:output:0"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node_def {
  name: "Identity"
  op: "Identity"
  input: "pow:z:0"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
ret {
  key: "identity"
  value: "Identity:output:0"
}
attr {
  key: "_construction_context"
  value {
    s: "kEagerRuntime"
  }
}
arg_attr {
  key: 0
  value {
    attr {
      key: "_output_shapes"
      value {
        list {
          shape {
            dim {
              size: 2
            }
        

## Tracing

In [85]:
@tf.function(input_signature=[tf.TensorSpec(shape=(None, 28, 28), dtype=tf.float32)])
def batched_shrink(images):
    return images[:, ::2, ::2]

In [86]:
batched_shrink.get_concrete_function(
    tf.random.uniform(shape=(128, 28, 28))
) is batched_shrink.get_concrete_function(tf.random.uniform(shape=(32, 28, 28)))

True

In [90]:
try:
    batched_shrink(tf.random.uniform(shape=(16, 2, 28)))
except TypeError as err:
    print(err)

Binding inputs to tf.function failed due to `Can not cast TensorSpec(shape=(16, 2, 28), dtype=tf.float32, name=None) to TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None)`. Received args: (<tf.Tensor: shape=(16, 2, 28), dtype=float32, numpy=
array([[[8.40849757e-01, 9.02973413e-01, 2.14023352e-01, 2.86659956e-01,
         3.09932113e-01, 8.37629557e-01, 7.69418836e-01, 1.17953062e-01,
         5.14299393e-01, 6.34467959e-01, 6.10469699e-01, 9.55732465e-01,
         8.41470122e-01, 5.39741993e-01, 2.84905314e-01, 3.65893841e-01,
         4.47809458e-01, 5.51259518e-02, 1.37994647e-01, 3.32277656e-01,
         9.77335215e-01, 2.72036314e-01, 7.90857553e-01, 1.77142620e-01,
         7.25242734e-01, 7.77873158e-01, 7.83225060e-01, 8.21829915e-01],
        [5.36910057e-01, 4.09068346e-01, 1.54609680e-02, 7.88566113e-01,
         8.03546906e-01, 8.08928370e-01, 5.54323077e-01, 3.39903593e-01,
         8.67890000e-01, 3.01780462e-01, 3.88722658e-01, 5.69292665e-01,
         5.88511

In [87]:
@tf.function
def shrink(images):
    return images[:, ::2, ::2]

In [88]:
shrink.get_concrete_function(
    tf.random.uniform(shape=(128, 28, 28))
) is shrink.get_concrete_function(tf.random.uniform(shape=(32, 28, 28)))

False

In [91]:
shrink(tf.random.uniform(shape=(16, 2, 28)))

<tf.Tensor: shape=(16, 1, 14), dtype=float32, numpy=
array([[[5.5466044e-01, 5.7885468e-01, 7.3367834e-02, 1.3519883e-01,
         8.1235993e-01, 3.4821796e-01, 8.2275414e-01, 1.8782938e-01,
         2.9290509e-01, 1.3511157e-01, 1.8290842e-01, 4.8319578e-02,
         6.0969758e-01, 3.0236268e-01]],

       [[4.6987057e-01, 6.9005466e-01, 8.6758709e-01, 8.3288431e-01,
         8.7908614e-01, 1.1861253e-01, 6.2187314e-01, 2.1616793e-01,
         4.2568839e-01, 5.5463839e-01, 8.5001683e-01, 3.5272396e-01,
         1.7925811e-01, 1.4986527e-01]],

       [[2.3521924e-01, 7.0750868e-01, 8.1413519e-01, 7.5246453e-01,
         6.4898860e-01, 9.0970278e-02, 5.8919466e-01, 8.8644862e-02,
         2.2734189e-01, 9.1975594e-01, 5.9229255e-02, 1.3014781e-01,
         4.0469003e-01, 6.3484824e-01]],

       [[9.5108485e-01, 6.9119644e-01, 4.0788651e-01, 3.5062480e-01,
         7.5474679e-01, 1.1422253e-01, 3.3159709e-01, 9.8407471e-01,
         2.1552801e-02, 1.5179634e-02, 5.2091646e-01, 2.817853

## Autograph

In [116]:
import tensorflow as tf


@tf.function
def add_10(x):
    cond = lambda i, x: tf.less(i, 10)

    # body = lambda i, x: (tf.add(i, 1), tf.add(x, 1))
    def body(i, x):
        print("Tracing...")
        tf.print("Executing...")
        return tf.add(i, 1), tf.add(x, 1)

    res_i, res_x = tf.while_loop(cond, body, [0, x])
    return res_x

In [117]:
add_10(tf.constant(1))

Tracing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...


<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [98]:
add_10.get_concrete_function(tf.constant(1)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=While>,
 <tf.Operation 'Identity' type=Identity>,
 <tf.Operation 'NoOp' type=NoOp>]

In [127]:
@tf.function
def stat_add_10(x):
    for i in range(10):
        print("Tracing...")
        tf.print("Executing...")
        x += 1
    return x

In [128]:
stat_add_10(tf.constant(1))

Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Tracing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...


<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [114]:
stat_add_10.get_concrete_function(tf.constant(10)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'add_1/y' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'add_2/y' type=Const>,
 <tf.Operation 'add_2' type=AddV2>,
 <tf.Operation 'add_3/y' type=Const>,
 <tf.Operation 'add_3' type=AddV2>,
 <tf.Operation 'add_4/y' type=Const>,
 <tf.Operation 'add_4' type=AddV2>,
 <tf.Operation 'add_5/y' type=Const>,
 <tf.Operation 'add_5' type=AddV2>,
 <tf.Operation 'add_6/y' type=Const>,
 <tf.Operation 'add_6' type=AddV2>,
 <tf.Operation 'add_7/y' type=Const>,
 <tf.Operation 'add_7' type=AddV2>,
 <tf.Operation 'add_8/y' type=Const>,
 <tf.Operation 'add_8' type=AddV2>,
 <tf.Operation 'add_9/y' type=Const>,
 <tf.Operation 'add_9' type=AddV2>,
 <tf.Operation 'Identity' type=Identity>]

In [124]:
@tf.function
def dyn_add_10(x):
    for i in tf.range(10):
        print("Tracing...")
        tf.print("Executing...")
        x += 1
    return x

In [125]:
dyn_add_10(tf.constant(1))

Tracing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...
Executing...


<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [126]:
dyn_add_10.get_concrete_function(tf.constant(10)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/limit' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'floordiv' type=FloorDiv>,
 <tf.Operation 'mod' type=FloorMod>,
 <tf.Operation 'zeros_like' type=Const>,
 <tf.Operation 'NotEqual' type=NotEqual>,
 <tf.Operation 'Cast' type=Cast>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'zeros_like_1' type=Const>,
 <tf.Operation 'Maximum' type=Maximum>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=While>,
 <tf.Operation 'Identity' type=Identity>,
 <tf.Operation 'NoOp' type=NoOp>]

In [136]:
cf = dyn_add_10.get_concrete_function(tf.constant(1))
(
    cf.graph.get_operation_by_name("while").inputs,
    cf.graph.get_operation_by_name("while").outputs,
)

((<tf.Tensor 'while/loop_counter:0' shape=() dtype=int32>,
  <tf.Tensor 'while/maximum_iterations:0' shape=() dtype=int32>,
  <tf.Tensor 'range/start:0' shape=() dtype=int32>,
  <tf.Tensor 'x:0' shape=() dtype=int32>,
  <tf.Tensor 'range/limit:0' shape=() dtype=int32>,
  <tf.Tensor 'range/delta:0' shape=() dtype=int32>),
 [<tf.Tensor 'while:0' shape=() dtype=int32>,
  <tf.Tensor 'while:1' shape=() dtype=int32>,
  <tf.Tensor 'while:2' shape=() dtype=int32>,
  <tf.Tensor 'while:3' shape=() dtype=int32>,
  <tf.Tensor 'while:4' shape=() dtype=int32>,
  <tf.Tensor 'while:5' shape=() dtype=int32>])